// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwCsvXSpfSF6CkGeF81sFKivbAjb4H4JI',
    appId: '1:403759544454:web:dad2727fe1a38fdc293907',
    messagingSenderId: '403759544454',
    projectId: 'kmstry-8510d',
    authDomain: 'kmstry-8510d.firebaseapp.com',
    storageBucket: 'kmstry-8510d.firebasestorage.app',
    measurementId: 'G-742Y97JREF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF47jkUhp_uoVV9jDz7r91n9oPvg80TH8',
    appId: '1:403759544454:android:6b3f376f72fd0f42293907',
    messagingSenderId: '403759544454',
    projectId: 'kmstry-8510d',
    storageBucket: 'kmstry-8510d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb5TqwL08pFZiE92M91u6O39H-EOgf7sA',
    appId: '1:403759544454:ios:78be3e698518ab37293907',
    messagingSenderId: '403759544454',
    projectId: 'kmstry-8510d',
    storageBucket: 'kmstry-8510d.firebasestorage.app',
    iosBundleId: 'com.deniz.kmstryFrontend.dev2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb5TqwL08pFZiE92M91u6O39H-EOgf7sA',
    appId: '1:403759544454:ios:9f03816d2490e806293907',
    messagingSenderId: '403759544454',
    projectId: 'kmstry-8510d',
    storageBucket: 'kmstry-8510d.firebasestorage.app',
    iosBundleId: 'com.example.kmstryFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwCsvXSpfSF6CkGeF81sFKivbAjb4H4JI',
    appId: '1:403759544454:web:7ff86b3b3ccc73da293907',
    messagingSenderId: '403759544454',
    projectId: 'kmstry-8510d',
    authDomain: 'kmstry-8510d.firebaseapp.com',
    storageBucket: 'kmstry-8510d.firebasestorage.app',
    measurementId: 'G-87HP3HR1PB',
  );
}
